"""Rule-based crop disease database for the expert system."""

CROPS = [
    {"id": "tomato", "name": "Tomato", "nameHi": "टमाटर"},
    {"id": "potato", "name": "Potato", "nameHi": "आलू"},
    {"id": "corn", "name": "Corn/Maize", "nameHi": "मक्का"},
    {"id": "rice", "name": "Rice", "nameHi": "धान"},
    {"id": "wheat", "name": "Wheat", "nameHi": "गेहूं"},
]

DISEASE_DATABASE = {
    "tomato": [
        {
            "id": "tomato_healthy",
            "name": "Healthy",
            "nameHi": "स्वस्थ",
            "severity": 0,
            "severityLevel": "none",
            "symptoms": ["green leaves", "no spots", "normal growth"],
            "symptomsHi": ["हरी पत्तियाँ", "कोई धब्बा नहीं", "सामान्य वृद्धि"],
            "visualPatterns": [],
            "treatment": {
                "organic": "Continue regular care. Ensure proper watering and sunlight.",
                "organicHi": "नियमित देखभाल जारी रखें। उचित सिंचाई और धूप सुनिश्चित करें।",
                "chemical": "No treatment needed.",
                "chemicalHi": "कोई उपचार आवश्यक नहीं।",
                "dosage": None,
                "dosageHi": None,
                "frequency": None,
                "frequencyHi": None,
            },
        },
        {
            "id": "tomato_early_blight",
            "name": "Early Blight",
            "nameHi": "अग्रिम झुलसा (Early Blight)",
            "severity": 6,
            "severityLevel": "medium",
            "symptoms": ["dark spots with concentric rings", "yellowing around spots"],
            "symptomsHi": ["केंद्रित छल्लों वाले गहरे धब्बे", "धब्बों के आसपास पीलापन"],
            "visualPatterns": ["brownSpots", "yellowEdges"],
            "treatment": {
                "organic": "Remove infected leaves. Apply neem oil spray.",
                "organicHi": "संक्रमित पत्तियाँ हटाएँ। नीम तेल का छिड़काव करें।",
                "chemical": "Apply Mancozeb or Chlorothalonil fungicide.",
                "chemicalHi": "मैंकोज़ेब या क्लोरोथैलोनिल fungicide का छिड़काव करें।",
                "dosage": "Mancozeb: 2.5g per liter of water",
                "dosageHi": "मैंकोज़ेब: 2.5 ग्राम प्रति लीटर पानी",
                "frequency": "Every 7-10 days until symptoms subside",
                "frequencyHi": "लक्षण कम होने तक हर 7-10 दिन",
            },
        },
        {
            "id": "tomato_late_blight",
            "name": "Late Blight",
            "nameHi": "झुलसा रोग (Leaf Blight)",
            "severity": 9,
            "severityLevel": "high",
            "symptoms": ["large water-soaked lesions", "white fuzzy growth", "rapid plant death"],
            "symptomsHi": ["पत्तियों पर भूरे और काले धब्बे", "पानी से भरे घाव", "तेज़ी से पौधे का सूखना"],
            "visualPatterns": ["brownSpots", "whiteMold", "waterSoaked"],
            "treatment": {
                "organic": "Remove and destroy infected plants immediately.",
                "organicHi": "संक्रमित पौधे तुरंत हटाएँ और नष्ट करें।",
                "chemical": "Apply Metalaxyl + Mancozeb (Ridomil Gold).",
                "chemicalHi": "कॉपर ऑक्सीक्लोराइड 50% WP (3 ग्राम प्रति लीटर पानी) का छिड़काव करें।",
                "dosage": "Ridomil Gold: 2g per liter of water",
                "dosageHi": "3 ग्राम प्रति लीटर पानी",
                "frequency": "Every 5-7 days during outbreak",
                "frequencyHi": "10 दिन बाद दोहराएँ",
            },
        },
    ],
    "potato": [
        {
            "id": "potato_healthy",
            "name": "Healthy",
            "nameHi": "स्वस्थ",
            "severity": 0,
            "severityLevel": "none",
            "symptoms": ["green leaves", "normal growth"],
            "symptomsHi": ["हरी पत्तियाँ", "सामान्य वृद्धि"],
            "visualPatterns": [],
            "treatment": {
                "organic": "Continue regular care.",
                "organicHi": "नियमित देखभाल जारी रखें।",
                "chemical": "No treatment needed.",
                "chemicalHi": "कोई उपचार आवश्यक नहीं।",
                "dosage": None,
                "dosageHi": None,
                "frequency": None,
                "frequencyHi": None,
            },
        },
        {
            "id": "potato_early_blight",
            "name": "Early Blight",
            "nameHi": "अग्रिम झुलसा",
            "severity": 6,
            "severityLevel": "medium",
            "symptoms": ["dark brown spots with rings", "yellowing leaves"],
            "symptomsHi": ["छल्लों वाले भूरे धब्बे", "पत्तियों का पीला होना"],
            "visualPatterns": ["brownSpots", "yellowEdges"],
            "treatment": {
                "organic": "Remove infected foliage. Apply copper fungicide.",
                "organicHi": "संक्रमित पत्तियाँ हटाएँ। कॉपर fungicide लगाएँ।",
                "chemical": "Apply Mancozeb or Chlorothalonil.",
                "chemicalHi": "मैंकोज़ेब या क्लोरोथैलोनिल का छिड़काव करें।",
                "dosage": "Mancozeb: 2.5g per liter",
                "dosageHi": "2.5 ग्राम प्रति लीटर पानी",
                "frequency": "Every 7-10 days",
                "frequencyHi": "हर 7-10 दिन",
            },
        },
        {
            "id": "potato_late_blight",
            "name": "Late Blight",
            "nameHi": "झुलसा रोग",
            "severity": 10,
            "severityLevel": "high",
            "symptoms": ["water-soaked lesions", "white mold on leaf undersides"],
            "symptomsHi": ["पानी से भरे घाव", "पत्तियों के नीचे सफेद फफूंद"],
            "visualPatterns": ["brownSpots", "whiteMold", "waterSoaked"],
            "treatment": {
                "organic": "URGENT: Remove and destroy all infected plants.",
                "organicHi": "तत्काल: सभी संक्रमित पौधे हटाएँ और नष्ट करें।",
                "chemical": "Apply Metalaxyl + Mancozeb immediately.",
                "chemicalHi": "तुरंत Ridomil Gold का छिड़काव करें।",
                "dosage": "Ridomil Gold: 2.5g per liter",
                "dosageHi": "2.5 ग्राम प्रति लीटर पानी",
                "frequency": "Every 5 days during outbreak",
                "frequencyHi": "प्रकोप के दौरान हर 5 दिन",
            },
        },
    ],
    "corn": [
        {
            "id": "corn_healthy",
            "name": "Healthy",
            "nameHi": "स्वस्थ",
            "severity": 0,
            "severityLevel": "none",
            "symptoms": ["green leaves", "normal tassel"],
            "symptomsHi": ["हरी पत्तियाँ", "सामान्य वृद्धि"],
            "visualPatterns": [],
            "treatment": {
                "organic": "Continue regular care.",
                "organicHi": "नियमित देखभाल जारी रखें।",
                "chemical": "No treatment needed.",
                "chemicalHi": "कोई उपचार आवश्यक नहीं।",
                "dosage": None,
                "dosageHi": None,
                "frequency": None,
                "frequencyHi": None,
            },
        },
        {
            "id": "corn_gray_leaf_spot",
            "name": "Gray Leaf Spot",
            "nameHi": "ग्रे लीफ स्पॉट",
            "severity": 6,
            "severityLevel": "medium",
            "symptoms": ["rectangular gray-brown lesions", "lower leaves affected first"],
            "symptomsHi": ["आयताकार भूरे धब्बे", "निचली पत्तियाँ पहले प्रभावित"],
            "visualPatterns": ["brownSpots"],
            "treatment": {
                "organic": "Crop rotation. Remove crop residue.",
                "organicHi": "फसल चक्र अपनाएँ। फसल अवशेष हटाएँ।",
                "chemical": "Apply Azoxystrobin fungicide.",
                "chemicalHi": "Azoxystrobin fungicide का छिड़काव करें।",
                "dosage": "1ml per liter of water",
                "dosageHi": "1 मिली प्रति लीटर पानी",
                "frequency": "Every 14 days",
                "frequencyHi": "हर 14 दिन",
            },
        },
        {
            "id": "corn_common_rust",
            "name": "Common Rust",
            "nameHi": "सामान्य रस्ट",
            "severity": 5,
            "severityLevel": "medium",
            "symptoms": ["orange-brown pustules", "dusty spores on leaves"],
            "symptomsHi": ["नारंगी-भूरे धब्बे", "पत्तियों पर धूल जैसे रंग"],
            "visualPatterns": ["rustColor"],
            "treatment": {
                "organic": "Usually self-limiting. Ensure good nutrition.",
                "organicHi": "आमतौर पर स्वयं ठीक हो जाता है। उचित पोषण दें।",
                "chemical": "Apply Propiconazole if severe.",
                "chemicalHi": "गंभीर होने पर Propiconazole लगाएँ।",
                "dosage": "1ml per liter",
                "dosageHi": "1 मिली प्रति लीटर",
                "frequency": "One application at first sign",
                "frequencyHi": "पहले लक्षण पर एक बार",
            },
        },
    ],
    "rice": [
        {
            "id": "rice_healthy",
            "name": "Healthy",
            "nameHi": "स्वस्थ",
            "severity": 0,
            "severityLevel": "none",
            "symptoms": ["green leaves", "normal tillering"],
            "symptomsHi": ["हरी पत्तियाँ", "सामान्य कुश/agronomy"],
            "visualPatterns": [],
            "treatment": {
                "organic": "Continue proper water management.",
                "organicHi": "उचित जल प्रबंधन जारी रखें।",
                "chemical": "No treatment needed.",
                "chemicalHi": "कोई उपचार आवश्यक नहीं।",
                "dosage": None,
                "dosageHi": None,
                "frequency": None,
                "frequencyHi": None,
            },
        },
        {
            "id": "rice_blast",
            "name": "Rice Blast",
            "nameHi": "धान ब्लास्ट",
            "severity": 9,
            "severityLevel": "high",
            "symptoms": ["diamond-shaped lesions", "gray center with brown border"],
            "symptomsHi": ["हीरे के आकार के घाव", "भूरे किनारे के साथ भूरा केंद्र"],
            "visualPatterns": ["brownSpots"],
            "treatment": {
                "organic": "Use resistant varieties. Apply Trichoderma.",
                "organicHi": "प्रतिरोधी किस्में उपयोग करें। Trichoderma लगाएँ।",
                "chemical": "Apply Tricyclazole or Isoprothiolane.",
                "chemicalHi": "Tricyclazole का छिड़काव करें।",
                "dosage": "0.6g per liter",
                "dosageHi": "0.6 ग्राम प्रति लीटर",
                "frequency": "Every 10-15 days",
                "frequencyHi": "हर 10-15 दिन",
            },
        },
        {
            "id": "rice_brown_spot",
            "name": "Brown Spot",
            "nameHi": "भूरा धब्बा रोग",
            "severity": 5,
            "severityLevel": "medium",
            "symptoms": ["oval brown spots", "dark brown margin"],
            "symptomsHi": ["अंडाकार भूरे धब्बे", "गहरे भूरे किनारे"],
            "visualPatterns": ["brownSpots"],
            "treatment": {
                "organic": "Improve soil fertility. Apply potassium.",
                "organicHi": "मिट्टी की उर्वरता बढ़ाएँ। पोटाश दें।",
                "chemical": "Apply Mancozeb or Propiconazole.",
                "chemicalHi": "मैंकोज़ेब का छिड़काव करें।",
                "dosage": "2.5g per liter",
                "dosageHi": "2.5 ग्राम प्रति लीटर",
                "frequency": "Every 10-15 days",
                "frequencyHi": "हर 10-15 दिन",
            },
        },
    ],
    "wheat": [
        {
            "id": "wheat_healthy",
            "name": "Healthy",
            "nameHi": "स्वस्थ",
            "severity": 0,
            "severityLevel": "none",
            "symptoms": ["green leaves", "normal tillering"],
            "symptomsHi": ["हरी पत्तियाँ", "सामान्य वृद्धि"],
            "visualPatterns": [],
            "treatment": {
                "organic": "Continue proper fertilization.",
                "organicHi": "उचित उर्वरक देना जारी रखें।",
                "chemical": "No treatment needed.",
                "chemicalHi": "कोई उपचार आवश्यक नहीं।",
                "dosage": None,
                "dosageHi": None,
                "frequency": None,
                "frequencyHi": None,
            },
        },
        {
            "id": "wheat_rust",
            "name": "Wheat Rust",
            "nameHi": "गेहूं रस्ट",
            "severity": 8,
            "severityLevel": "high",
            "symptoms": ["orange-brown pustules", "yellow stripes"],
            "symptomsHi": ["नारंगी-भूरे धब्बे", "पीली धारियाँ"],
            "visualPatterns": ["rustColor"],
            "treatment": {
                "organic": "Use resistant varieties.",
                "organicHi": "प्रतिरोधी किस्में उपयोग करें।",
                "chemical": "Apply Propiconazole or Tebuconazole.",
                "chemicalHi": "Propiconazole का छिड़काव करें।",
                "dosage": "1ml per liter",
                "dosageHi": "1 मिली प्रति लीटर",
                "frequency": "At first sign, repeat after 15 days",
                "frequencyHi": "पहले लक्षण पर, 15 दिन बाद दोहराएँ",
            },
        },
        {
            "id": "wheat_septoria",
            "name": "Septoria Leaf Blotch",
            "nameHi": "झुलसा रोग (Leaf Blight)",
            "severity": 6,
            "severityLevel": "medium",
            "symptoms": ["tan lesions with dark specks", "progresses up plant"],
            "symptomsHi": ["पत्तियों पर भूरे और काले धब्बे", "पौधे पर ऊपर की ओर फैलता है"],
            "visualPatterns": ["brownSpots", "blackSpots"],
            "treatment": {
                "organic": "Crop rotation. Remove infected residue.",
                "organicHi": "फसल चक्र अपनाएँ। संक्रमित अवशेष हटाएँ।",
                "chemical": "Apply Azoxystrobin + Cyproconazole.",
                "chemicalHi": "कॉपर ऑक्सीक्लोराइड 50% WP (3 ग्राम प्रति लीटर पानी) का छिड़काव करें।",
                "dosage": "1ml Azoxystrobin per liter",
                "dosageHi": "3 ग्राम प्रति लीटर पानी",
                "frequency": "At flag leaf emergence",
                "frequencyHi": "10 दिन बाद दोहराएँ",
            },
        },
        {
            "id": "wheat_powdery_mildew",
            "name": "Powdery Mildew",
            "nameHi": "पाउडरी मिल्ड्यू",
            "severity": 5,
            "severityLevel": "medium",
            "symptoms": ["white powdery patches", "starts on lower leaves"],
            "symptomsHi": ["सफेद पाउडर जैसी परत", "निचली पत्तियों से शुरू"],
            "visualPatterns": ["whiteMold"],
            "treatment": {
                "organic": "Good air circulation. Apply potassium silicate.",
                "organicHi": "हवा का प्रवाह बढ़ाएँ।",
                "chemical": "Apply Sulfur or Propiconazole.",
                "chemicalHi": "सल्फर WP का छिड़काव करें।",
                "dosage": "3g Sulfur per liter",
                "dosageHi": "3 ग्राम प्रति लीटर",
                "frequency": "Every 10-15 days",
                "frequencyHi": "हर 10-15 दिन",
            },
        },
    ],
}


def get_diseases_for_crop(crop_id: str):
    return DISEASE_DATABASE.get(crop_id, DISEASE_DATABASE["wheat"])
